### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by su787910081** [apolloconfig/apollo-java#13]
- [ ] 我已经检查过[discussions](https://github.com/apolloconfig/apollo-java/discussions)
- [ ] 我已经搜索过[issues](https://github.com/apolloconfig/apollo-java/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
在apollo-client 模块里面，`SpringValueDefinitionProcessor` 中有如下代码块：
```java
  public static Multimap<String, SpringValueDefinition> getBeanName2SpringValueDefinitions(BeanDefinitionRegistry registry) {
    Multimap<String, SpringValueDefinition> springValueDefinitions = beanName2SpringValueDefinitions.get(registry);
    if (springValueDefinitions == null) {
      springValueDefinitions = LinkedListMultimap.create();
    }

    return springValueDefinitions;
  }
```

这段代码我怎么看着有点迷糊，当不存在时，就新那一个返回出去，但是这个新建的对象并没有保存下来，也就是说当我多次调用时，返回的是不同的实例对象，那这段代码有什么意义呢？

其次没有加锁

对于目前来说似乎没有问题，但看样子是因为这里的调用总是不会返回null，因为`SpringValueDefinitionProcessor` 是`BeanDefinitionRegistryPostProcessor` 而`SpringValueProcessor` 是`BeanFactoryPostProcessor`， `BeanDefinitionRegistryPostProcessor` 的运行优先级比`BeanFactoryPostProcessor` 高，所以在`SpringValueDefinitionProcessor` 已经初始化了，所以在`SpringValueProcessor` 中调用`SpringValueDefinitionProcessor.getBeanName2SpringValueDefinitions(..)` 这个方法的时候总是存在值了。

单看这一个方法它的逻辑是有问题的，但从spring 的整体机制来讲这个BUG 不会触发。

简洁明了地描述一下bug
。

**复现**
。

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
> 当不存在时，就新那一个返回出去，但是这个新建的对象并没有保存下来，也就是说当我多次调用时，返回的是不同的实例对象

这确实是个 bug

> 其次没有加锁

这个方法是 postProcessBeanFactory 调用的，不会有并发问题，所以不需要加锁
