### ISSUE TITLE
是否有不使用Springboot3.0的高版本SDK？

### ISSUE THREAD

**Issue by chenke3** [apolloconfig/apollo-java#26]
我看到很多BUG的fix是在2.1.0的版本上，老的版本，比如1.7.0没有合并这些fix，而2.1.0的版本使用了Springboot3.0要求JDK17，这块对于存量业务系统不太友好，是否有兼容JDK8的最新版本SDK？

**Comment by nobodyiam** [comment]
2.1.0 支持 jdk8+，包含了 jdk 17，spring boot 也是一样，支持 spring boot 1.x/2.x/3.x
