### ISSUE TITLE
无法加载ServiceLoader.load

### ISSUE THREAD

**Issue by Songjiadong** [apolloconfig/apollo-java#28]
我使用apollo往es ik插件进行集成的时候，发现报类似app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!（举个例子）
这种的提示，但实际上我已经往META-INFO 中加入了相关的配置，我将java-client的源码拿来跟踪了一下 发现是

 public static <S> Iterator<S> loadAll(Class<S> clazz) {

    ServiceLoader<S> loader = ServiceLoader.load(clazz);

    return loader.iterator();
  }
这个load加载不进去，是否能够帮忙看一下，我打完包 看了一下jar包，结构里有META-INF\services\....，不知道是什么原因就是无法加载，由于es的版本必须是jdk18.0.2,所以我用的jdk是18.0.2，centos7的操作系统

![image](https://github.com/apolloconfig/apollo-java/assets/46697885/c5a08462-1bb7-462e-a603-28f015442a91)

**Comment by nobodyiam** [comment]
这个问题应该就是找不到 `META-INF/services/com.ctrip.framework.foundation.spi.ProviderManager` 文件，或者文件内容为空。

**Comment by Songjiadong** [comment]
> 这个问题应该就是找不到 `META-INF/services/com.ctrip.framework.foundation.spi.ProviderManager` 文件，或者文件内容为空。
我在网上查了一般情况确实是你说的情况，但是我看了源码 您说的这些内容我都不缺，所以不是您说的原因。
这个问题我今天在调试的时候找到原因了 我将ServiceBootstrap.java源代码作如下修改就可以了，
 public static <S> Iterator<S> loadAll(Class<S> clazz) {
    ClassLoader cl=ServiceBootstrap.class.getClassLoader();
    ServiceLoader<S> loader = ServiceLoader.load(clazz,cl);

    return loader.iterator();
  }
个人感觉应该是个bug，源代码采用的是默认的方式即 ServiceLoader<S> loader = ServiceLoader.load(clazz);查看里面，它默认的cl是  ClassLoader cl = Thread.currentThread().getContextClassLoader();即：
public static <S> ServiceLoader<S> load(Class<S> service) {
        ClassLoader cl = Thread.currentThread().getContextClassLoader();
        return new ServiceLoader<>(Reflection.getCallerClass(), service, cl);
    }
而在es ik plugin中调用恰好cl不是当前的cl，您可以试一试?
感谢您的回复，谢谢

**Comment by nobodyiam** [comment]
看起来 es 在执行的时候改变了 class loader，不过我这里没有 es 的测试环境，你能帮忙测试并提交一个 Patch 吗？

**Comment by Songjiadong** [comment]
> 看起来 es 在执行的时候改变了 class loader，不过我这里没有 es 的测试环境，你能帮忙测试并提交一个 Patch 吗？
好的,我抽时间弄一下
