### ISSUE TITLE
Support for loading apollo modules through SPI

### ISSUE THREAD

**Issue by Tian90coder** [apolloconfig/apollo-java#33]
The current method of loading Apollo Module is fixed and difficult to expand.
Can we support for loading apollo modules through SPI?

<img width="970" alt="image" src="https://github.com/apolloconfig/apollo-java/assets/56345542/16608b3b-b776-4465-ac36-f432a7ee6507">

**Comment by nobodyiam** [comment]
There are several places for customizing the modules, which, in my opinion, could be suitable for most scenarios.
1. The injector itself is loaded via [SPI](https://github.com/apolloconfig/apollo-java/blob/e4d12c734bd52cf768317486a72cc32d4aa0c0cb/apollo-client/src/main/java/com/ctrip/framework/apollo/build/ApolloInjector.java#L36).
2. The default injector features a [ApolloInjectorCustomizer](https://github.com/apolloconfig/apollo-java/blob/e4d12c734bd52cf768317486a72cc32d4aa0c0cb/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultInjector.java#L63-L68) mechanism.

Could there be a situation that I've overlooked?
