### ISSUE TITLE
when to release  2.2.0 version

### ISSUE THREAD

**Issue by huntkalio** [apolloconfig/apollo-java#39]
we wan't to use new version because to fix snakeyaml bug : https://github.com/apolloconfig/apollo-java/pull/35

**Comment by nobodyiam** [comment]
It may take some time as the [create app function](https://github.com/apolloconfig/apollo-java/pull/32) is still ongoing. However you may use the [snapshot](https://oss.sonatype.org/#nexus-search;gav~com.ctrip.framework.apollo~apollo-client~2.2.0-SNAPSHOT~~) version if it's urgent.
