### ISSUE TITLE
apolli-client 2.1.0 can not work with snakeyaml 2.x

### ISSUE THREAD

**Issue by luger1990** [apolloconfig/apollo-java#40]
![17c42e18-f78f-4eb0-8dbc-aee2d45e68ac](https://github.com/apolloconfig/apollo-java/assets/2096878/6e650988-cb0a-4308-b952-787f7fb5aa6c)
our project use snakeyaml 2.x, but apollo use snakeyaml 1.29. so i hope the apollo-client can upgrade to snakeyaml 2.x. 
thanks
for more info you can check here https://stackoverflow.com/questions/75947862/getting-java-lang-nosuchmethoderror-org-yaml-snakeyaml-constructor-safeconstruc

**Comment by nobodyiam** [comment]
see #35

**Comment by luger1990** [comment]
> see #35

cool
