### ISSUE TITLE
yaml里配置List<String> aaa= [],解析后变成null而非空字符串列表

### ISSUE THREAD

**Issue by xusida** [apolloconfig/apollo-java#41]
https://github.com/apolloconfig/apollo-java/blob/f8d28868e5c300bca0161885a316cce3639bd342/apollo-client/src/main/java/com/ctrip/framework/apollo/util/yaml/YamlParser.java#L156

此处转换properties，会忽略空List，这和springboot解析yaml文件结果不一致，此处影响原springboot yaml文件迁移到apollo，最后导致生产NPE错误

spring YamlProcessor: https://github.com/spring-projects/spring-framework/blob/620bce5527a120a528e884e6b26facda4ba1f730/spring-beans/src/main/java/org/springframework/beans/factory/config/YamlProcessor.java#L333

**Comment by nobodyiam** [comment]
Thank you for bringing this to our attention. It appears that the YamlParser employed in the Apollo project is derived from Spring 4.x releases, while the logic for empty collection checks was introduced in Spring 5.1.0. Could you kindly verify if other logic components have been omitted and, if so, consider submitting a pull request?
