### ISSUE TITLE
parse yaml configuration fail when upgrade the spring boot

### ISSUE THREAD

**Issue by cjdxhjj** [apolloconfig/apollo-java#45]
- [ ] I have checked the [discussions](https://github.com/apolloconfig/apollo-java/discussions)
- [ ] I have searched the [issues](https://github.com/apolloconfig/apollo-java/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://www.apolloconfig.com/#/en/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
![image](https://github.com/apolloconfig/apollo-java/assets/5616997/81718ad4-96b9-411c-98b3-07c8b2e7915d)

**To Reproduce**
1. upgrade spring boot to 3.2.0 or upgrade snakeyaml to 2.2

2023-11-24 16:31:49,268 [main] WARN [cas] DefaultConfig Init Apollo Local Config failed - namespace: application.yaml, reason: Parse yaml file content failed for namespace: application.yaml [Cause: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found].

the snakeyaml remove the default no arg constructor
![image](https://github.com/apolloconfig/apollo-java/assets/5616997/df3d7997-bd55-4ebd-8e33-f60ecf067eb3)
the 1.29 was
![image](https://github.com/apolloconfig/apollo-java/assets/5616997/7f363f30-ccd2-4a5d-8423-9cb7251554c7)

**Expected behavior**

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
Thanks, it was fixed by #35

**Comment by cjdxhjj** [comment]
When is the version released?

**Comment by nobodyiam** [comment]
It's likely that the release will be next month. In the meantime, if it's urgent, you can use the [snapshot version](https://oss.sonatype.org/#nexus-search;gav~com.ctrip.framework.apollo~apollo-client~2.2.0-SNAPSHOT~~).

**Comment by cjdxhjj** [comment]
thanks, i would wait for the next release

**Comment by nobodyiam** [comment]
Apollo java version 2.2.0 is now available for download. You can access this latest release at [Maven Central](https://search.maven.org/search?q=com.ctrip.framework.apollo).

**Comment by cjdxhjj** [comment]
thanks
