### ISSUE TITLE
ApolloJsonValue注解增加部分自定义功能

### ISSUE THREAD

**Issue by yesterday11** [apolloconfig/apollo-java#49]
**现状：**
目前ApolloJsonValue仅支持从portal读取指定配置，没有其他功能支持。在遇到下面场景时显得有些无奈：
假如在配置中有一些日期时间相关的配置，如下：

`{
    "beginTime": "2019-08-21 00:00:00",
    "endTime": "2019-09-05 00:00:00",
    "switch": true
}`

在接收对应的时间按配置时只能用String（如果直接用Date接受，会报错：Failed to parse date ["2019-08-21 00:00:00"]: Invalid time zone indicator ' '），然后在代码中进行格式化。
**建议：**
ApolloJsonValue增加一个 dateFormat ，ApolloJsonValueProcessor在解析式可以用指定的格式去解析

**Comment by nobodyiam** [comment]
@huxleyliau thanks for the reminder, it's transferred now.

**Comment by huxleyliau** [comment]
Sorry about that. I made a mistake and accidentally closed [PR](https://github.com/apolloconfig/apollo-java/pull/52). :broken_heart:  Could you kindly reopen it, or should I submit a new PR? :sob: I don't have the authority to do that. @nobodyiam 
![image](https://github.com/apolloconfig/apollo-java/assets/154882442/341cbd11-7b99-4365-9a18-84874c57455c)

**Comment by nobodyiam** [comment]
It's reopened.

**Comment by nobodyiam** [comment]
@huxleyliau would you please submit a new pr? I can't make the cla assistant work on the old pr..

**Comment by huxleyliau** [comment]
> @huxleyliau would you please submit a new pr? I can't make the cla assistant work on the old pr..

Got it. I'll now submit a new PR.

**Comment by huxleyliau** [comment]
> @huxleyliau would you please submit a new pr? I can't make the cla assistant work on the old pr..

Before closing this [PR](https://github.com/apolloconfig/apollo-java/pull/52), I wasn't able to create a new one. Could you please close it again? I don't have the authority to do that close this [PR](https://github.com/apolloconfig/apollo-java/pull/52). :joy:
![image](https://github.com/apolloconfig/apollo-java/assets/154882442/5dd88763-956c-47d1-baf8-10df99113ade)

**Comment by nobodyiam** [comment]
#52 is closed.
