### ISSUE TITLE
Allow injecting dynamic config to ApolloConfigChangeListener

### ISSUE THREAD

**Issue by anandjoshisn** [apolloconfig/apollo-java#7]
**Is your feature request related to a problem? Please describe.**
The annotation ApolloConfigChangeListener takes an array of string (values = String []), which means if I have some namespaces defined in an `application.yaml ` as comma separated values, I can't inject it as it needs to be constant.

**Describe the solution you'd like**
Either of the two solutions are fine 
1. Allow spring expression evaluation. eg - `@ApolloConfigChangeListener("#{'${prop.apollo.namespaces:}'.split(',')}")`
2. Provide an optional argument. eg - `@ApolloConfigChangeListener(namespaces = "${prop.apollo.namespaces}")`

Here my `application.yaml` would be

```yaml
prop:
  apollo:
    namespaces: "foo,bar,other-namespace"

```

PS - I can share a sample PR if I can have permission on this repo.

**Comment by anandjoshisn** [comment]
PR - https://github.com/apolloconfig/apollo-java/pull/8

**Comment by nobodyiam** [comment]
I believe apollo-client already supports the use of placeholders like `@ApolloConfigChangeListener("${prop.apollo.namespaces}")`, see https://github.com/apolloconfig/apollo/pull/3349.

So the proposed feature is to
1. support the Spring expression
    * I'm not sure whether this is a strong requirement since Spring expression is not commonly used in my experience
2. support configuring a list of namespaces as a placeholder
    * This could be a good feature, what do you think @Anilople ?

**Comment by anandjoshi91** [comment]
Thanks @nobodyiam  for your feedback. As per your suggestion I have opened PR for point 2 - https://github.com/apolloconfig/apollo-java/pull/11
